- name: Updates Pi-hole
  hosts: dns
  serial: 1
  become: yes

  vars:
    telegram_bot_token_1: "{{ lookup('env', 'TELEGRAM_BOT_TOKEN_1') }}"
    telegram_chat_id_1: "{{ lookup('env', 'TELEGRAM_CHAT_ID_1') }}"

  tasks:
    - name: Check if server is pingable
      ansible.builtin.ping:
      register: ansible_ping_result

    - name: Updating Pi-hole
      command: pihole -up
      register: pihole_update_result
      changed_when: "'Update complete' in pihole_update_result.stdout"
      when: ansible_ping_result.ping == 'pong'

    - name: Reboot server after updating Pi-hole
      ansible.builtin.reboot:
      when: pihole_update_result.changed and ansible_ping_result.ping == 'pong'

    - name: Wait for server to come back after reboot
      wait_for_connection:
        timeout: 300
      when: pihole_update_result.changed

    - name: Check if server is pingable after reboot
      ansible.builtin.ping:
      register: ansible_ping_after_reboot
      when: pihole_update_result.changed

    - name: Send Telegram notification about updates
      telegram:
        token: "{{ telegram_bot_token_1 }}"
        api_args:
          chat_id: "{{ telegram_chat_id_1 }}"
          parse_mode: "markdown"
          text: "Pi-hole on {{ ansible_hostname }} updated ✅"
          disable_web_page_preview: true
          disable_notification: true
      when: pihole_update_result.changed and ansible_ping_after_reboot.ping == 'pong'